doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '15'
  orm:
    auto_generate_proxy_classes: true
    enable_lazy_ghost_objects: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App\src\Shop\Domain\Cart:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Shop/Infrastructure/Persistance/Doctrine/Mapping/Cart'
        prefix: 'App\Shop\Domain\Cart'
      App\src\Shop\Domain\Product:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Shop/Infrastructure/Persistance/Doctrine/Mapping/Product'
        prefix: 'App\Shop\Domain\Product'
      App\src\Shop\Domain\User:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Shop/Infrastructure/Persistance/Doctrine/Mapping/User'
        prefix: 'App\Shop\Domain\User'
      App\src\Shop\Domain\Product\PriceVO:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Shop/Infrastructure/Persistance/Doctrine/Mapping/Product/PriceVO'
        prefix: 'App\Shop\Domain\Product\PriceVO'
  
when@test:
  doctrine:
    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
      dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
