version: '3'

services:
  php:
    build: ./
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
      - ./docker/:/etc/apache2/sites-available/
    working_dir: /var/www/html/
      
  database:
    image: 'mysql:latest'
    environment:
      MYSQL_USER: siro
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cart-api-db
    ports:
      # To allow the host machine to access the ports below, modify the lines below.
      # For example, to allow the host to connect to port 3306 on the container, you would change
      # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
      # See https://docs.docker.com/compose/compose-file/compose-file-v3/#ports for more information.
      - '3306:3306'
 
